# Generated by Django 2.0.5 on 2018-06-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='store.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=288, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=160, unique=True),
        ),
    ]
