# Generated by Django 2.0.5 on 2018-06-05 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180605_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='private_token',
        ),
        migrations.RemoveField(
            model_name='order',
            name='public_token',
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
