# Generated by Django 2.0.5 on 2018-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart', 'product')},
        ),
    ]
